# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aed86ac47e41bbe5c242bfb69f22f21dd5b4ca359a8669ebfa6ab7f53482fc58c4cef2608921e2949df841a5b242606437540745e2c2c6b44c5b006cd24cefd8

test:
  secret_key_base: d45858911642d6c07315e83fafc4bf8d133a9c4bf7e566cf8ff4ec2da1c99dc54874125267817bff45b412c9b691399dc14f0420565b23fd896ccd5a1cf5b86d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
